local Emitter = {}
function Emitter.emit(module) local lines = { "-- generated by LC-lang" }; for _, fn in ipairs(module.functions) do lines[#lines + 1] = "function " .. fn.name .. "() end" end; return table.concat(lines, "\n") end
return Emitter
